### ISSUE TITLE
Remove django (and maybe PIL) from install_requires

### ISSUE THREAD

**Issue by kmike** [vasyl-stanislavchuk/django-imperavi#1]
Hi,

Can you please remove django from install_requires? It make no sense to install django via installing django-imperavi + this may cause issues:
- if django is installed via symlink or pip install -e git+... then "pip install django-imperavi" will overwrite this installed version (that's because django doesn't use setuptools and so setuptools can't reliably determine if django is installed);
- "pip install -U django-imperavi" can upgrade django even if this is not what developer need.

IMHO PIL should be also removed from install_requires because many people use http://pypi.python.org/pypi/Pillow instead of PIL (this is a friendly fork that fixed a number of packaging issues with PIL that makes it hard to build PIL on some platforms).

**Comment by vasyl-stanislavchuk** [comment]
Thanks for comments and interest.
